stages:
  - list
  - test

.test:
  stage: test
  before_script:
    - mkdir .reports
  artifacts:
    reports:
      junit: .reports/tests.xml

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

python 3.7 test:
  extends: .test
  image: registry.gitlab.com/potato-oss/google-cloud/django-gcloud-connectors/python37:latest
  script: tox -e py37 -- --junitxml=.reports/tests.xml

python 3.6 test:
  extends: .test
  image: registry.gitlab.com/potato-oss/google-cloud/django-gcloud-connectors/python36:latest
  script: tox -e py36 -- --junitxml=.reports/tests.xml


flake8:
  image: registry.gitlab.com/potato-oss/google-cloud/django-gcloud-connectors/python37:latest
  before_script:
    - mkdir .reports
  script: tox -e flake8 -- --format junit-xml --output-file=".reports/flake8.xml"
  artifacts:
    reports:
      junit: .reports/flake8.xml
